[package]
name = "guest"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
sp1-zkvm = { workspace = true }
kzg-rs-blend = { path = "../crates/kzg-rs-blend", default-features = false }

